package dev

import (
	"fmt"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/anurag925/crank/internal/bootstrap"
	"github.com/anurag925/crank/internal/bootstrap/tools"
	"github.com/anurag925/crank/internal/utils"
)

func init() {
	bootstrap.GlobalToolRegistry.MustRegister(tool{})
}

type tool struct{}

func (tool) Name() string               { return "dev" }
func (tool) BinaryName() string         { return "air" }
func (tool) Description() string        { return "Run with live reload (air)" }
func (tool) RequiresFeatures() []string { return nil }

func (tool) LongDescription() string {
	return `dev starts the project using 'air' for live reload during development.
Requires an .air.toml in the project root (generated by default with base feature).

If --project is not specified, the current directory is used.

Examples:
  crank dev --project ./myapp
  cd myapp && crank dev                            (uses current directory)`
}

func (tool) InstallCmd() string {
	return "go install github.com/air-verse/air@latest"
}

func (t tool) Install() error {
	return tools.InstallGoTool("github.com/air-verse/air@latest", t.BinaryName(), "")
}

func (tool) AddFlags(cmd *cobra.Command) {}

func (tool) Prepare(projectDir string, cmd *cobra.Command, extraArgs []string) (*bootstrap.ToolInvocation, error) {
	toml := filepath.Join(projectDir, ".air.toml")
	if !utils.PathExists(toml) {
		return nil, fmt.Errorf("no .air.toml found in %s", projectDir)
	}
	return &bootstrap.ToolInvocation{Args: extraArgs, Dir: projectDir, Stdin: true}, nil
}
