package e2e

// Tests for backward compatibility — projects generated by older crank
// versions (or with hand-edited manifests) must continue to work with
// newer crank binaries.
//
// The code paths under test:
//   - Old project without `// crank:handler-fields` markers in
//     internal/handler/handler.go. `crank make handler` must use the
//     brace-based fallback wiring (spliceAtBraces).
//   - Manifest without `crank_version` (e.g. user deleted the line).
//   - Manifest without `module_path` (must fall back to go.mod).
//   - Manifest completely missing (Add must error, Make must error).
//   - Corrupt manifest (Add must error with a YAML-friendly message).

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// Handler wiring: brace-based fallback for old projects
// ---------------------------------------------------------------------------

// TestE2E_Backcompat_NoHandlerMarkers_BraceWiring simulates a project
// generated before the `// crank:handler-*` markers existed. The
// generated handler.go has the Handler struct, New() and Register(), but
// NO `crank:handler-fields`, `crank:handler-init` or
// `crank:handler-register` comments.
//
// `crank make handler Foo` must still wire the new handler in via the
// brace-based fallback (spliceAtBraces) and produce a project that
// compiles.
func TestE2E_Backcompat_NoHandlerMarkers_BraceWiring(t *testing.T) {
	dir := scaffoldBase(t, "backcompat_no_markers")

	// Strip the marker comments from handler.go.
	handlerPath := filepath.Join(dir, "internal/handler/handler.go")
	orig, err := os.ReadFile(handlerPath)
	if err != nil {
		t.Fatalf("read handler.go: %v", err)
	}
	stripped := orig
	for _, marker := range []string{
		"// crank:handler-fields (do not remove — `crank make handler` inserts fields here)",
		"// crank:handler-init (do not remove — `crank make handler` inserts initializers here)",
		"// crank:handler-register (do not remove — `crank make handler` inserts route registrations here)",
	} {
		stripped = []byte(strings.ReplaceAll(string(stripped), marker, ""))
	}
	if err := os.WriteFile(handlerPath, stripped, 0o644); err != nil {
		t.Fatalf("rewrite handler.go: %v", err)
	}

	// Generate a new handler; wiring must use the brace-based fallback.
	runCrank(t, "", "make", "handler", "Comment", "body:string", "--project", dir)

	// The handler must be registered.
	hub := readFile(t, dir, "internal/handler/handler.go")
	if !strings.Contains(hub, "h.comments.Register(e)") {
		t.Errorf("handler.go missing comments registration after brace-based wiring:\n%s", hub)
	}
	if !strings.Contains(hub, "comments *CommentHandler") {
		t.Errorf("handler.go missing comments field in struct after brace-based wiring:\n%s", hub)
	}

	// The whole project must still compile.
	compileProject(t, dir)
}

// TestE2E_Backcompat_NoWorkerMarkers_BraceWiring is the temporal analog:
// the worker.go in a "pre-marker" temporal project must still register a
// new workflow/activity. (Currently the temporal feature always emits
// markers, so this is more of a regression test for the future.)
func TestE2E_Backcompat_NoWorkerMarkers_BraceWiring(t *testing.T) {
	dir := scaffold(t, "backcompat_no_worker_markers", []string{"temporal"})

	// Strip the marker comments from worker.go.
	workerPath := filepath.Join(dir, "pkg/temporal/worker.go")
	orig, err := os.ReadFile(workerPath)
	if err != nil {
		t.Fatalf("read worker.go: %v", err)
	}
	stripped := orig
	for _, marker := range []string{
		"// crank:workflow-register",
		"// crank:activity-register",
	} {
		stripped = []byte(strings.ReplaceAll(string(stripped), marker, ""))
	}
	if err := os.WriteFile(workerPath, stripped, 0o644); err != nil {
		t.Fatalf("rewrite worker.go: %v", err)
	}

	// The wiring code path is best-effort; if markers are missing it
	// returns a Hint instead of writing. We just want to confirm no
	// panic and the project still compiles.
	out, err := runCrankRaw(t, "", "make", "workflow", "LegacyFlow", "--project", dir)
	_ = out
	_ = err
	compileProject(t, dir)
}

// ---------------------------------------------------------------------------
// Manifest variants
// ---------------------------------------------------------------------------

// TestE2E_Backcompat_ManifestWithoutVersion verifies that a manifest
// missing the `crank_version` field can still be read and that Add works
// against it.
func TestE2E_Backcompat_ManifestWithoutVersion(t *testing.T) {
	dir := scaffoldBaseRaw(t, "backcompat_no_version")
	writeManifestRaw(t, dir, `project_name: myapp
module_path: github.com/example/myapp
features:
  - base
`)
	// Add a feature; the manifest must be re-written with a version.
	runCrank(t, "", "add", "crypto", "--project", dir)
	updated := readFile(t, dir, ".crank.yaml")
	if !strings.Contains(updated, "crank_version:") {
		t.Errorf("post-add manifest missing crank_version field:\n%s", updated)
	}
	if !strings.Contains(updated, "- crypto") {
		t.Errorf("post-add manifest missing crypto feature:\n%s", updated)
	}
}

// TestE2E_Backcompat_ManifestWithoutModulePath_FallsBackToGoMod verifies
// the LoadProjectInfo fallback: if the manifest's module_path is empty,
// the module is read from go.mod.
func TestE2E_Backcompat_ManifestWithoutModulePath_FallsBackToGoMod(t *testing.T) {
	dir := scaffoldBaseRaw(t, "backcompat_no_module")
	writeManifestRaw(t, dir, `project_name: myapp
crank_version: dev
features:
  - base
`)
	// Update go.mod with a known module path.
	modPath := "github.com/example/backcompat_nomodule"
	if err := os.WriteFile(
		filepath.Join(dir, "go.mod"),
		[]byte("module "+modPath+"\n\ngo 1.21\n"),
		0o644,
	); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	info := loadManifest(t, dir)
	if info.ModulePath != modPath {
		t.Errorf("LoadProjectInfo: module path = %q, want %q", info.ModulePath, modPath)
	}
}

// TestE2E_Backcompat_ManifestWithoutModuleOrGoMod falls all the way back
// to the project name.
func TestE2E_Backcompat_ManifestWithoutModuleOrGoMod(t *testing.T) {
	dir := scaffoldBaseRaw(t, "backcompat_no_module_no_gomod")
	writeManifestRaw(t, dir, `project_name: myapp
crank_version: dev
features:
  - base
`)
	// Drop go.mod.
	if err := os.Remove(filepath.Join(dir, "go.mod")); err != nil {
		t.Fatalf("remove go.mod: %v", err)
	}

	info := loadManifest(t, dir)
	if info.ModulePath != "myapp" {
		t.Errorf("LoadProjectInfo: module path = %q, want fallback to project name", info.ModulePath)
	}
}

// TestE2E_Backcompat_CorruptManifest_AddErrors ensures that a project
// with malformed YAML in its manifest surfaces a clean error from
// `crank add` (rather than panicking or producing a stack trace).
func TestE2E_Backcompat_CorruptManifest_AddErrors(t *testing.T) {
	dir := scaffoldBaseRaw(t, "backcompat_corrupt")
	writeManifestRaw(t, dir, "this is: : not: valid: yaml: [\n")
	out, err := runCrankRaw(t, "", "add", "crypto", "--project", dir)
	if err == nil {
		t.Fatalf("expected YAML parse error, got success:\n%s", out)
	}
}

// TestE2E_Backcompat_EmptyManifest_AddErrors covers an empty (zero-byte)
// .crank.yaml file. The Add command treats empty YAML as a valid (empty)
// manifest and proceeds to add the feature. The new feature's
// `crank add` succeeds (since there's no existing-feature conflict) and
// the resulting manifest now contains only the new feature.
func TestE2E_Backcompat_EmptyManifest_AddErrors(t *testing.T) {
	dir := scaffoldBaseRaw(t, "backcompat_empty")
	writeManifestRaw(t, dir, "")
	runCrank(t, "", "add", "crypto", "--project", dir)
	manifest := readFile(t, dir, ".crank.yaml")
	if !strings.Contains(manifest, "- crypto") {
		t.Errorf("manifest should contain crypto after add:\n%s", manifest)
	}
}

// TestE2E_Backcompat_MakeOnProjectWithoutManifest covers `crank make` on
// a project that has no manifest. Make must error (it needs the
// module path from the manifest).
func TestE2E_Backcompat_MakeOnProjectWithoutManifest(t *testing.T) {
	dir := scaffoldBaseRaw(t, "backcompat_make_no_manifest")
	removeManifest(t, dir)
	out, err := runCrankRaw(t, "", "make", "model", "X", "--project", dir)
	if err == nil {
		t.Fatalf("expected error, got success:\n%s", out)
	}
	if !strings.Contains(out, "manifest") && !strings.Contains(out, ".crank.yaml") {
		t.Errorf("error should mention manifest, got:\n%s", out)
	}
}

// TestE2E_Backcompat_MakeOnProjectWithMissingGoMod: even with a valid
// manifest, Make fails if go.mod is missing. (Make uses LoadProjectInfo
// to discover the module path; a missing go.mod is OK only if the
// manifest has a module_path.)
func TestE2E_Backcompat_MakeOnProjectWithManifestButNoGoMod(t *testing.T) {
	dir := scaffoldBaseRaw(t, "backcompat_make_no_gomod")
	if err := os.Remove(filepath.Join(dir, "go.mod")); err != nil {
		t.Fatalf("remove go.mod: %v", err)
	}
	// Manifest has the module path baked in, so Make should still work.
	runCrank(t, "", "make", "model", "Orphaned", "name:string", "--project", dir)
	assertExists(t, dir, "internal/model/orphaned.go")
}

// ---------------------------------------------------------------------------
// Old feature set still accepted
// ---------------------------------------------------------------------------

// TestE2E_Backcompat_OldManifestWithExtraUnknownFeature verifies that
// extra features in the manifest that crank no longer recognizes (or
// never knew) don't break LoadProjectInfo or Add.
func TestE2E_Backcompat_OldManifestWithExtraUnknownFeature(t *testing.T) {
	dir := scaffoldBaseRaw(t, "backcompat_extra_feature")
	writeManifestRaw(t, dir, `project_name: myapp
module_path: github.com/example/myapp
crank_version: dev
features:
  - base
  - experimental-long-since-removed
`)
	// Add a valid feature; the unknown one should be preserved in the
	// manifest as-is (we never rewrite the order, just append).
	runCrank(t, "", "add", "crypto", "--project", dir)
	updated := readFile(t, dir, ".crank.yaml")
	if !strings.Contains(updated, "- crypto") {
		t.Errorf("post-add manifest missing crypto:\n%s", updated)
	}
	if !strings.Contains(updated, "experimental-long-since-removed") {
		t.Errorf("post-add manifest lost the unknown feature:\n%s", updated)
	}
}

// TestE2E_Backcompat_OldManifestWithBaseInMiddle verifies the order
// independence of features in the manifest. The base feature must
// remain present regardless of where it appears in the original list.
// (Unlike fresh generations where base is first, the Add function does
// NOT reorder an existing base in the middle — it preserves the user's
// ordering and just appends the new feature.)
//
// We don't actually run `crank add` (which would invoke `go get` and
// fail if the manifest's module path doesn't match the project name).
// Instead we manipulate the manifest directly to confirm the manifest
// is rewritten in a normalized order.
func TestE2E_Backcompat_OldManifestWithBaseInMiddle(t *testing.T) {
	dir := scaffoldBaseRaw(t, "backcompat_base_in_middle")
	// Build a manifest whose module_path matches the project name.
	writeManifestRaw(t, dir, `project_name: backcompat_base_in_middle
module_path: github.com/example/backcompat_base_in_middle
crank_version: dev
features:
  - crypto
  - base
  - redis
`)
	// Use the in-process Add function to rewrite the manifest with a
	// normalized feature list. We use bootstrap.Add (not the binary) so
	// no `go get` is triggered.
	_, err := bootstrapAddForCompat(t, dir, "mongodb")
	if err != nil {
		t.Fatalf("bootstrap.Add: %v", err)
	}
	updated := readFile(t, dir, ".crank.yaml")
	if !strings.Contains(updated, "- base") {
		t.Errorf("base lost after add:\n%s", updated)
	}
	if !strings.Contains(updated, "- mongodb") {
		t.Errorf("mongodb not appended after add:\n%s", updated)
	}
}
