package e2e

// Tests that verify a project generated by crank can itself be operated
// on by crank. This is the highest-value end-to-end coverage: it proves
// the entire pipeline (init → go get → make → build → test) is self-
// consistent and the generated project plays well with the tool that
// produced it.
//
// The tests in this file use --project to target the generated project
// from outside (so we don't depend on PATH containing the crank binary),
// with two exceptions that simulate the user running `crank <cmd>` from
// inside the project (we add the crank binary to PATH for those).

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestE2E_Generated_VetFromOutside runs `crank vet --project=./myapp`
// against a generated project from a separate working directory.
// Verifies the binary works the same whether invoked from inside or
// outside the project.
func TestE2E_Generated_VetFromOutside(t *testing.T) {
	dir := scaffoldBase(t, "gen_vet")
	other := t.TempDir()
	runCrank(t, other, "vet", "--project", dir)
}

// TestE2E_Generated_BuildFromOutside: similar to above, but for build.
// The binary must produce a bin/<name> artifact.
func TestE2E_Generated_BuildFromOutside(t *testing.T) {
	dir := scaffoldBase(t, "gen_build")
	other := t.TempDir()
	runCrank(t, other, "build", "--project", dir)
	binary := filepath.Join(dir, "bin", filepath.Base(dir))
	if _, err := os.Stat(binary); err != nil {
		t.Errorf("expected build artifact at %s: %v", binary, err)
	}
}

// TestE2E_Generated_TestFromOutside: `crank test --project` runs the
// generated project's own test suite.
func TestE2E_Generated_TestFromOutside(t *testing.T) {
	dir := scaffoldBase(t, "gen_test")
	other := t.TempDir()
	runCrank(t, other, "test", "--project", dir)
}

// TestE2E_Generated_TidyFromOutside: `crank tidy --project` is a no-op on
// a freshly init'd project.
func TestE2E_Generated_TidyFromOutside(t *testing.T) {
	dir := scaffoldBase(t, "gen_tidy")
	other := t.TempDir()
	runCrank(t, other, "tidy", "--project", dir)
}

// TestE2E_Generated_GofmtFromOutside: `crank gofmt --project` is a no-op
// on a freshly init'd (already-formatted) project.
func TestE2E_Generated_GofmtFromOutside(t *testing.T) {
	dir := scaffoldBase(t, "gen_gofmt")
	other := t.TempDir()
	runCrank(t, other, "gofmt", "--project", dir)
}

// TestE2E_Generated_ListFromOutside: `crank list` lists the features
// available to the (base) project. The command is global; it does not
// accept a --project flag.
func TestE2E_Generated_ListFromOutside(t *testing.T) {
	_ = scaffoldBase(t, "gen_list")
	other := t.TempDir()
	out := runCrank(t, other, "list")
	for _, f := range allFeatureNames {
		if !strings.Contains(out, f) {
			t.Errorf("list missing feature %q:\n%s", f, out)
		}
	}
}

// TestE2E_Generated_ToolsListFromOutside: `crank tools` lists every
// tool wrapper. Tools are global and do not take a --project flag.
func TestE2E_Generated_ToolsListFromOutside(t *testing.T) {
	_ = scaffoldBase(t, "gen_tools_list")
	other := t.TempDir()
	out := runCrank(t, other, "tools")
	for _, tool := range allToolNames {
		if !strings.Contains(out, tool) {
			t.Errorf("tools list missing %q:\n%s", tool, out)
		}
	}
}

// TestE2E_Generated_VersionFromProject verifies the user can run
// `crank --version` from inside the generated project (PATH has the
// crank binary).
func TestE2E_Generated_VersionFromProject(t *testing.T) {
	dir := scaffoldBase(t, "gen_version")
	// The crank binary built in TestMain lives in the test binary's
	// directory; we put the project on PATH and let it find crank.
	crankPath := filepath.Dir(crankBin)
	out := runCrankWithEnv(t, dir, []string{"PATH=" + crankPath + string(os.PathListSeparator) + os.Getenv("PATH")}, "--version")
	if !strings.Contains(out, "crank version") {
		t.Errorf("expected version output, got:\n%s", out)
	}
}

// TestE2E_Generated_MakeFromProject verifies the user can run
// `crank make model X` from inside the generated project.
func TestE2E_Generated_MakeFromProject(t *testing.T) {
	dir := scaffoldBase(t, "gen_make")
	crankPath := filepath.Dir(crankBin)
	env := []string{"PATH=" + crankPath + string(os.PathListSeparator) + os.Getenv("PATH")}
	runCrankWithEnv(t, dir, env, "make", "model", "Foo", "name:string")
	assertExists(t, dir, "internal/domain/foo/foo.go")
}

// TestE2E_Generated_AddFromProject verifies the user can run
// `crank add <feature>` from inside the generated project.
func TestE2E_Generated_AddFromProject(t *testing.T) {
	dir := scaffoldBase(t, "gen_add")
	crankPath := filepath.Dir(crankBin)
	env := []string{"PATH=" + crankPath + string(os.PathListSeparator) + os.Getenv("PATH")}
	runCrankWithEnv(t, dir, env, "add", "crypto")
	manifest := readFile(t, dir, ".crank.yaml")
	if !strings.Contains(manifest, "- crypto") {
		t.Errorf("manifest missing crypto after add-from-project:\n%s", manifest)
	}
}

// TestE2E_Generated_BinDirectoryCreated verifies the `bin/` directory is
// created by the first `crank build` invocation (the build tool's
// `-o bin/...` flag creates it as a side effect of go build).
func TestE2E_Generated_BinDirectoryCreated(t *testing.T) {
	dir := scaffoldBase(t, "gen_bin")
	runCrank(t, "", "build", "--project", dir)
	if _, err := os.Stat(filepath.Join(dir, "bin")); err != nil {
		t.Errorf("expected bin/ directory to exist after build: %v", err)
	}
}

// TestE2E_Generated_RunFromProject_StartAndKill: a "smoke test" for the
// server. We start `crank run` in the background, wait briefly, send a
// SIGTERM, and assert the process exited cleanly. This proves the
// generated main.go boots, parses config, and serves a request without
// panicking.
//
// We skip this test on platforms where the timeout doesn't work, and we
// also skip if the test would interfere with other tests sharing a port
// (we use port 0 binding in the generated config? — actually, we don't,
// so we patch configs/config.yaml to use a high port).
func TestE2E_Generated_RunFromProject_StartAndKill(t *testing.T) {
	dir := scaffoldBase(t, "gen_run")

	// Use a high port that's unlikely to be in use.
	yamlPath := filepath.Join(dir, "configs", "config.yaml")
	yamlBody := readFile(t, dir, "configs/config.yaml")
	yamlBody = strings.Replace(yamlBody, "port: 8080", "port: 18080", 1)
	yamlBody = strings.Replace(yamlBody, "host: \"0.0.0.0\"", "host: \"127.0.0.1\"", 1)
	if err := os.WriteFile(yamlPath, []byte(yamlBody), 0o644); err != nil {
		t.Fatalf("write config.yaml: %v", err)
	}

	crankPath := filepath.Dir(crankBin)
	env := []string{
		"PATH=" + crankPath + string(os.PathListSeparator) + os.Getenv("PATH"),
	}
	cmd, err := startCrankCommand(t, dir, env, "run", "--project", dir)
	if err != nil {
		t.Fatalf("start run: %v", err)
	}
	// Give the server a moment to boot. We don't need it to fully
	// respond to HTTP — we just need it to not crash within the first
	// half-second.
	waitFor(t, 500) // ms
	stopCommand(t, cmd)
}

// TestE2E_Generated_ProjectHasCleanTarget verifies the Makefile that
// ships with every generated project defines a `clean` target. This
// pre-condition is what makes `crank clean` work via Makefile delegation.
func TestE2E_Generated_ProjectHasCleanTarget(t *testing.T) {
	dir := scaffoldBase(t, "gen_clean_target")
	body := readFile(t, dir, "Makefile")
	if !strings.Contains(body, "clean:") {
		t.Errorf("generated Makefile missing 'clean:' target:\n%s", body)
	}
}

// TestE2E_Generated_ProjectHasAirToml verifies the .air.toml is created
// (so `crank dev` will work once air is installed).
func TestE2E_Generated_ProjectHasAirToml(t *testing.T) {
	dir := scaffoldBase(t, "gen_air_toml")
	assertExists(t, dir, ".air.toml")
}

// TestE2E_Generated_ProjectHasDockerfile verifies the Dockerfile is
// created. (The README points users at this for production deploys.)
func TestE2E_Generated_ProjectHasDockerfile(t *testing.T) {
	dir := scaffoldBase(t, "gen_dockerfile")
	assertExists(t, dir, "Dockerfile")
}

// TestE2E_Generated_ProjectHasGitignore verifies the .gitignore is
// created. (bin/, docs/, etc. should be excluded.)
func TestE2E_Generated_ProjectHasGitignore(t *testing.T) {
	dir := scaffoldBase(t, "gen_gitignore")
	assertExists(t, dir, ".gitignore")
	body := readFile(t, dir, ".gitignore")
	if !strings.Contains(body, "bin/") {
		t.Errorf(".gitignore missing bin/ exclusion:\n%s", body)
	}
}

// TestE2E_Generated_ProjectHasReadme verifies the README.md is created.
func TestE2E_Generated_ProjectHasReadme(t *testing.T) {
	dir := scaffoldBase(t, "gen_readme")
	assertExists(t, dir, "README.md")
}

// TestE2E_Generated_ProjectHasEnvExample verifies .env.example is created
// (a template users can copy to .env).
func TestE2E_Generated_ProjectHasEnvExample(t *testing.T) {
	dir := scaffoldBase(t, "gen_env_example")
	assertExists(t, dir, ".env.example")
}

// TestE2E_Generated_ProjectManifestAccurate verifies the .crank.yaml
// accurately reflects the project state (project_name, module_path,
// features list, crank_version).
func TestE2E_Generated_ProjectManifestAccurate(t *testing.T) {
	dir := scaffoldBase(t, "gen_manifest")
	manifest := readFile(t, dir, ".crank.yaml")
	for _, want := range []string{
		"project_name: " + filepath.Base(dir),
		"module_path: github.com/example/" + filepath.Base(dir),
		"crank_version:",
		"- base",
	} {
		if !strings.Contains(manifest, want) {
			t.Errorf("manifest missing %q:\n%s", want, manifest)
		}
	}
}

// TestE2E_Generated_ProjectGoModAccurate verifies go.mod is consistent
// with the module_path in the manifest.
func TestE2E_Generated_ProjectGoModAccurate(t *testing.T) {
	dir := scaffoldBase(t, "gen_go_mod")
	gomod := readFile(t, dir, "go.mod")
	want := "module github.com/example/" + filepath.Base(dir)
	if !strings.HasPrefix(gomod, want) {
		t.Errorf("go.mod does not start with %q:\n%s", want, gomod)
	}
}

// TestE2E_Generated_ProjectMainImportsConfig verifies the main.go in
// cmd/server uses the project's module path to import the config package.
func TestE2E_Generated_ProjectMainImportsConfig(t *testing.T) {
	dir := scaffoldBase(t, "gen_main_imports")
	main := readFile(t, dir, "cmd/server/main.go")
	want := "github.com/example/" + filepath.Base(dir) + "/internal/config"
	if !strings.Contains(main, want) {
		t.Errorf("main.go missing import %q:\n%s", want, main)
	}
}

// TestE2E_Generated_FeatureCommandsCompose verifies the "compose and
// run" workflow: init → make scaffold → add feature → make scaffold →
// build. The whole thing must succeed end to end.
func TestE2E_Generated_FeatureCommandsCompose(t *testing.T) {
	dir := scaffold(t, "gen_compose", []string{"base", "gorm"})

	// Make a scaffold.
	runCrank(t, "", "make", "scaffold", "Customer", "name:string", "--project", dir)
	// Add another feature.
	runCrank(t, "", "add", "crypto", "--project", dir)
	// Make another scaffold.
	runCrank(t, "", "make", "scaffold", "Token", "value:string", "--project", dir)
	// Build the whole thing.
	runCrank(t, "", "build", "--project", dir)
	binary := filepath.Join(dir, "bin", filepath.Base(dir))
	if _, err := os.Stat(binary); err != nil {
		t.Errorf("expected build artifact at %s: %v", binary, err)
	}
}
